### PR TITLE
Add CI build process, add CI environment properties file

### PR DESCRIPTION
**Pull request by drtechie**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.  

# Type of change  

- [ ] Bug fix  
- [ ] New feature  
- [x] Enhancement  
- [ ] Refactoring  
- [ ] Documentation  
- [x] Other ( please specify )  CI build process

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- Tested by packaging the application

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by drtechie** [comment]
@devikasuresh20, @ravishanigarapu 

1. I didn't see `fetosense-api-url-ANCTestDetails` property used anywhere in the application code.
2. The property points to `https://asia-south1-amrit-fetosense.cloudfunctions.net/insertMother` in test env whereas in other places it points to a different endpoint that to to localhost. Is this correct?
3. There was a `fetosenseAPIKey` key present in test env but not in others. I have added it to other envs and removed the value.

**Comment by devikasuresh20** [comment]
> @devikasuresh20, @ravishanigarapu
> 
> 1. I didn't see `fetosense-api-url-ANCTestDetails` property used anywhere in the application code.
> 2. The property points to `https://asia-south1-amrit-fetosense.cloudfunctions.net/insertMother` in test env whereas in other places it points to a different endpoint that to to localhost. Is this correct?
> 3. There was a `fetosenseAPIKey` key present in test env but not in others. I have added it to other envs and removed the value.


Yes I verified. It's not using anywhere.

**Comment by drtechie** [comment]
@devikasuresh20 @ravishanigarapu 

Found instances of the property usage here:
https://github.com/PSMRI/TM-API/blob/develop/src/main/java/com/iemr/tm/service/foetalmonitor/FoetalMonitorServiceImpl.java#L70

**Review by ravishanigarapu — APPROVED** [review]
looks fine

**Pull request merged**
